// src/pkjs/settings/holiday-data.js — ES5, PKJS-parsed. Option data for the holiday
// country/region selectors in schema.js. Country values are ISO-3166-1 alpha-2 (UK = GB);
// region values are full ISO-3166-2 codes. UI-only: nothing on the watch consumes these yet.

// [label, value] pairs. None first, United States second, then European (alphabetical by name).
var COUNTRY_OPTIONS = [
  ['None', 'none'],
  ['United States', 'US'],
  ['Austria', 'AT'],
  ['Belgium', 'BE'],
  ['Bulgaria', 'BG'],
  ['Croatia', 'HR'],
  ['Cyprus', 'CY'],
  ['Czechia', 'CZ'],
  ['Denmark', 'DK'],
  ['Estonia', 'EE'],
  ['Finland', 'FI'],
  ['France', 'FR'],
  ['Germany', 'DE'],
  ['Greece', 'GR'],
  ['Hungary', 'HU'],
  ['Iceland', 'IS'],
  ['Ireland', 'IE'],
  ['Italy', 'IT'],
  ['Latvia', 'LV'],
  ['Liechtenstein', 'LI'],
  ['Lithuania', 'LT'],
  ['Luxembourg', 'LU'],
  ['Malta', 'MT'],
  ['Netherlands', 'NL'],
  ['Norway', 'NO'],
  ['Poland', 'PL'],
  ['Portugal', 'PT'],
  ['Romania', 'RO'],
  ['Slovakia', 'SK'],
  ['Slovenia', 'SI'],
  ['Spain', 'ES'],
  ['Sweden', 'SE'],
  ['Switzerland', 'CH'],
  ['United Kingdom', 'GB']
];

// Region sub-selector options, keyed by country code. First entry is always the
// nationwide sentinel ['Whole country', 'all']; the rest are ISO-3166-2 subdivisions.
var REGION_OPTIONS = {
  DE: [
    ['Whole country', 'all'],
    ['Baden-Württemberg', 'DE-BW'],
    ['Bavaria', 'DE-BY'],
    ['Berlin', 'DE-BE'],
    ['Brandenburg', 'DE-BB'],
    ['Bremen', 'DE-HB'],
    ['Hamburg', 'DE-HH'],
    ['Hesse', 'DE-HE'],
    ['Mecklenburg-Vorpommern', 'DE-MV'],
    ['Lower Saxony', 'DE-NI'],
    ['North Rhine-Westphalia', 'DE-NW'],
    ['Rhineland-Palatinate', 'DE-RP'],
    ['Saarland', 'DE-SL'],
    ['Saxony', 'DE-SN'],
    ['Saxony-Anhalt', 'DE-ST'],
    ['Schleswig-Holstein', 'DE-SH'],
    ['Thuringia', 'DE-TH']
  ],
  AT: [
    ['Whole country', 'all'],
    ['Burgenland', 'AT-1'],
    ['Carinthia', 'AT-2'],
    ['Lower Austria', 'AT-3'],
    ['Upper Austria', 'AT-4'],
    ['Salzburg', 'AT-5'],
    ['Styria', 'AT-6'],
    ['Tyrol', 'AT-7'],
    ['Vorarlberg', 'AT-8'],
    ['Vienna', 'AT-9']
  ],
  CH: [
    ['Whole country', 'all'],
    ['Zürich', 'CH-ZH'],
    ['Bern', 'CH-BE'],
    ['Lucerne', 'CH-LU'],
    ['Uri', 'CH-UR'],
    ['Schwyz', 'CH-SZ'],
    ['Obwalden', 'CH-OW'],
    ['Nidwalden', 'CH-NW'],
    ['Glarus', 'CH-GL'],
    ['Zug', 'CH-ZG'],
    ['Fribourg', 'CH-FR'],
    ['Solothurn', 'CH-SO'],
    ['Basel-Stadt', 'CH-BS'],
    ['Basel-Landschaft', 'CH-BL'],
    ['Schaffhausen', 'CH-SH'],
    ['Appenzell Ausserrhoden', 'CH-AR'],
    ['Appenzell Innerrhoden', 'CH-AI'],
    ['St. Gallen', 'CH-SG'],
    ['Graubünden', 'CH-GR'],
    ['Aargau', 'CH-AG'],
    ['Thurgau', 'CH-TG'],
    ['Ticino', 'CH-TI'],
    ['Vaud', 'CH-VD'],
    ['Valais', 'CH-VS'],
    ['Neuchâtel', 'CH-NE'],
    ['Geneva', 'CH-GE'],
    ['Jura', 'CH-JU']
  ],
  ES: [
    ['Whole country', 'all'],
    ['Andalusia', 'ES-AN'],
    ['Aragon', 'ES-AR'],
    ['Asturias', 'ES-AS'],
    ['Canary Islands', 'ES-CN'],
    ['Cantabria', 'ES-CB'],
    ['Castile and León', 'ES-CL'],
    ['Castilla-La Mancha', 'ES-CM'],
    ['Catalonia', 'ES-CT'],
    ['Extremadura', 'ES-EX'],
    ['Galicia', 'ES-GA'],
    ['Balearic Islands', 'ES-IB'],
    ['La Rioja', 'ES-RI'],
    ['Madrid', 'ES-MD'],
    ['Murcia', 'ES-MC'],
    ['Navarre', 'ES-NC'],
    ['Basque Country', 'ES-PV'],
    ['Valencian Community', 'ES-VC'],
    ['Ceuta', 'ES-CE'],
    ['Melilla', 'ES-ML']
  ],
  GB: [
    ['Whole country', 'all'],
    ['England', 'GB-ENG'],
    ['Scotland', 'GB-SCT'],
    ['Wales', 'GB-WLS'],
    ['Northern Ireland', 'GB-NIR']
  ],
  US: [
    ['Whole country', 'all'],
    ['Alabama', 'US-AL'],
    ['Alaska', 'US-AK'],
    ['Arizona', 'US-AZ'],
    ['Arkansas', 'US-AR'],
    ['California', 'US-CA'],
    ['Colorado', 'US-CO'],
    ['Connecticut', 'US-CT'],
    ['Delaware', 'US-DE'],
    ['Florida', 'US-FL'],
    ['Georgia', 'US-GA'],
    ['Hawaii', 'US-HI'],
    ['Idaho', 'US-ID'],
    ['Illinois', 'US-IL'],
    ['Indiana', 'US-IN'],
    ['Iowa', 'US-IA'],
    ['Kansas', 'US-KS'],
    ['Kentucky', 'US-KY'],
    ['Louisiana', 'US-LA'],
    ['Maine', 'US-ME'],
    ['Maryland', 'US-MD'],
    ['Massachusetts', 'US-MA'],
    ['Michigan', 'US-MI'],
    ['Minnesota', 'US-MN'],
    ['Mississippi', 'US-MS'],
    ['Missouri', 'US-MO'],
    ['Montana', 'US-MT'],
    ['Nebraska', 'US-NE'],
    ['Nevada', 'US-NV'],
    ['New Hampshire', 'US-NH'],
    ['New Jersey', 'US-NJ'],
    ['New Mexico', 'US-NM'],
    ['New York', 'US-NY'],
    ['North Carolina', 'US-NC'],
    ['North Dakota', 'US-ND'],
    ['Ohio', 'US-OH'],
    ['Oklahoma', 'US-OK'],
    ['Oregon', 'US-OR'],
    ['Pennsylvania', 'US-PA'],
    ['Rhode Island', 'US-RI'],
    ['South Carolina', 'US-SC'],
    ['South Dakota', 'US-SD'],
    ['Tennessee', 'US-TN'],
    ['Texas', 'US-TX'],
    ['Utah', 'US-UT'],
    ['Vermont', 'US-VT'],
    ['Virginia', 'US-VA'],
    ['Washington', 'US-WA'],
    ['West Virginia', 'US-WV'],
    ['Wisconsin', 'US-WI'],
    ['Wyoming', 'US-WY'],
    ['District of Columbia', 'US-DC']
  ]
};

module.exports = {
  COUNTRY_OPTIONS: COUNTRY_OPTIONS,
  REGION_OPTIONS: REGION_OPTIONS
};
